### ISSUE TITLE
Can't find book

### ISSUE THREAD

**Issue by denaefordrobin** [FrustratedGameDev/Papers#1]
Should we withdraw book from reviews lists?

**Comment by anthonye2007** [comment]
Not sure what you're saying -- you talking about the book you got from the library?  Is it missing? If so, not sure where it is... I haven't been able to look at it yet.

**Comment by denaefordrobin** [comment]
@anthonye2007 Yes I am talking about the book from the library. 

I think we have a nice list of other sources. We may be able to remove this from our list of papers to find dimensions for.

**Comment by anthonye2007** [comment]
Sure, I've added the notes from the interview I read to the repo.  If we want to use those notes we can. I feel like the book would be great to read more of for my personal gain, but the papers are becoming more useful for this class.
