### ISSUE TITLE
Labor and Monopoly Capital

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#15]

**Comment by denaefordrobin** [comment]
Link : https://books.google.com/books?hl=en&lr=&id=uCgZwOH15s0C&oi=fnd&pg=PP2&dq=Labor+and+Monopoly+Capital&ots=cclz13nGYG&sig=vrQBnm7O6qzjSpx7sgGYNbWU8Xs#v=onepage&q=Labor%20and%20Monopoly%20Capital&f=false

The link to this ebook discusses the degradation of work in the twentieth. It discusses the general aspects that make work a pain for our society. The specific circumstance to games and software developers have been covered in multiple other dimensions. For example: 
- user fun
- user engagement
- social interaction
- work ownership and many others.
