### ISSUE TITLE
Making Great Games

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#16]

**Comment by denaefordrobin** [comment]
Link : http://gac.sagepub.com/content/1/1/36.short

# Full Article Title: Playing and Making Games for Learning Instructionist and Constructionist Perspectives for Game Studies

This article discusses how the process of making games can enhance the overall learning process. This process does not talk about the specific stress of games vs software developers. It does talk about the process and that is already covered in dimensions.
