### ISSUE TITLE
User Communities and Social Software in the Video Game Industry

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#23]

**Comment by denaefordrobin** [comment]
Link: http://www.sciencedirect.com/science/article/pii/S0024630111000446

This paper discussed how the Social Community of games has increased the interest of Social Games.  Social games has already been defined as a dimension in the repgrid.

**Comment by dmford** [comment]
Link:  http://www.sciencedirect.com/science/article/pii/S0024630111000446

This paper discusses how the social aspects of games have encouraged the concept of social games. The dimension of Social games has already been discussed in the repgrid.
