### ISSUE TITLE
A Survey on a State of the Practice in Video Game Development

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#29]

**Comment by anthonye2007** [comment]
Need to add abstract to repo

**Comment by anthonye2007** [comment]
http://www.researchgate.net/publication/242659876_A_Survey_on_a_State_of_the_Practice_in_Video_Game_Development

**Comment by anthonye2007** [comment]
Surveyed the Austrian games industry to understand what the state of the art practices were for game developers.

Found:
- small and young studios
- ad-hoc / flexible development processes

**Comment by anthonye2007** [comment]
Research questions:
1. Studio distribution (big or small studios)
2. Process Support and Method Application (e.g. automated testing)
3. Feature creep and crunch time affliction.

**Comment by anthonye2007** [comment]
small studios due to immature Austrian games industry

**Comment by anthonye2007** [comment]
gets some differences of AAA and indies

**Comment by anthonye2007** [comment]
table of tools used by which studios

**Comment by anthonye2007** [comment]
Adds dimension for small company vs large company

**Comment by denaefordrobin** [comment]
This is a great dimension which builds on the interview we had with our Games Industry representative.
