### ISSUE TITLE
Focusing on Direction of Project

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#32]
We realized Game Devs vs software devs isn't quite right for the 510 project.  What should we do instead?

**Comment by anthonye2007** [comment]
Still want to focus on game developers.
Two questions:
1. The game industry lifestyle reportedly sucks. Why do developers stay?
2. What are the stressors that game devs encounter?

**Comment by anthonye2007** [comment]
We talked with a former game dev (anonynous) in an unofficial interview. Gave lots of detail about games industry.

pointed out that there are two main kinds of game companies today
indy devs (with like 2 ppl on the team) and AAA games with more like 100s of ppl on the team
they seem very different, so we might want to pick one of the two to focus on
i'd lean towards indy as they are more likely to actually change if we can convince them to. big companies will be less likely to take our advice...

**Comment by anthonye2007** [comment]
@dmford can you add your chat notes here for a record?

**Comment by denaefordrobin** [comment]
I was thinking we could compare the two of them. Indy vs AAA. The lifestyle of their developers vary and I think that is something worth talking about. There is also a great value in sitting down and interviewing local game companies like Epic.

**Comment by denaefordrobin** [comment]
As far as the course is concerned we can hint(in the report) towards a study that compares the development process and after the course we can continue the study. Comments?

**Comment by anthonye2007** [comment]
Just found a great article #33 !!  Talks about indie studios vs AAA studios.  I went through all the references and added them as issues to GitHub.  Looks really useful.

**Comment by anthonye2007** [comment]
You may want to check out Jennifer Whitson, the author of the above paper.  Lots of interesting research on games. Nice overview of some recent games research here: http://tag.hexagram.ca/digra-overview-whats-happening-in-game-developer-research/

**Comment by anthonye2007** [comment]
Just saw her PhD is in Sociology -- so she'll have some interesting ideas outside of CS.

**Comment by anthonye2007** [comment]
After talking this morning, we decided to look at all these papers and see how they differ.  Milestones have been defined.
