### ISSUE TITLE
Can crowdsourcing revolutionise indie funding? 

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#39]

**Comment by denaefordrobin** [comment]
I don't think this paper adds a dimension. From what I understand it compares funding sources for games companies. Not relevant to general Software development. ....

Unless it is the fact  that Software Developers don't have to find funding for project but games companies do... I suppose. 

What do you think @anthonye2007

**Comment by denaefordrobin** [comment]
Paper has been added to the repo. 

The dimension added compares the funding which is already available in RepGrid
