### ISSUE TITLE
How Shaba’s ex-boss escaped from the “great middle”

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#45]
http://www.gamasutra.com/view/news/34798/Interview_How_Shaba_ExBoss_Escaped_
From_The_Great_Middle.php

**Comment by denaefordrobin** [comment]
Interesting paper. It only really talks about transitioning from between different parts of the games industry.  Doesn't compare Games development to Software development. Doesn't discuss the development process. It just generally discusses the industry.

**Comment by denaefordrobin** [comment]
Paper discusses  small company vs large company
