### ISSUE TITLE
International Game Developers Association. (2004). Quality of life white paper

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#46]
http://www.igda.org/quality-life-white-paper-info

**Comment by denaefordrobin** [comment]
Found revised link for paper: http://c.ymcdn.com/sites/www.igda.org/resource/collection/9215B88F-2AA3-4471-B44D-B5D58FF25DC7/2004_IGDA_QualityOfLife_WhitePaper.pdf?hhSearchTerms=%22quality+and+life%22

**Comment by denaefordrobin** [comment]
Summary has been added to PapersReviewed Repo.

I am now going through and pulling out the dimensions for the grid.
--quality of life 
 --work life balance 
 --long hours extended crunches 
 --high turnover 
 --job stability 
 --ownership of work

**Comment by denaefordrobin** [comment]
Actually added. dimension of 
high turnover vs. low turnover 
high job stability vs. low job stability
high ownership of work vs. low ownership of work.

**Comment by denaefordrobin** [comment]
Because of the great detail this article goes in I would classify it as a key article.
