### ISSUE TITLE
Digital play: The interaction of technology, culture, and marketing

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#47]

**Comment by denaefordrobin** [comment]
I have read this book via google books. It talks about the dimension of labour but does not go in depth on comparison between software development and games development.

Link to book: https://books.google.com/books?hl=en&lr=&id=VRJoRICMbzYC&oi=fnd&pg=PR7&dq=Digital+play:+The+interaction+of+technology,+culture,+and+marketing&ots=09alGdj7mV&sig=vLyz9Q3hhxusw2y4fEqjvgf2WoM#v=onepage&q&f=false
