### ISSUE TITLE
 Plagiarism is just what we do!

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#55]
http://www.gamasutra.com/view/news/38660/Opinion_Plagiarism_Is_Just_What_We_D
o.php

**Comment by anthonye2007** [comment]
"The question is not whether but how much to copy."

**Comment by anthonye2007** [comment]
How do we define copying?  What about reusing familiar interaction paradigms like WASD?

**Comment by anthonye2007** [comment]
Remember when "sandbox" games were "GTA clones" or "first-person shooters" (FPSs) were "Doom clones"?

**Comment by anthonye2007** [comment]
this is related to the 'constructivism' thought of another paper #14 .

**Comment by anthonye2007** [comment]
builds on the idea creation vs constructionism dimension already established.

**Comment by denaefordrobin** [comment]
Good. I don't think we need to go any further with this.
