### ISSUE TITLE
The crowdfunding revolution: Perspectives. 

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#58]
http://www.gamasutra.com/view/feature/6353/the_crowdfunding_revolution_.php

**Comment by anthonye2007** [comment]
Driving question: can indie devs get the money they need from crowdfunding?

**Comment by anthonye2007** [comment]
big factor in determining crowdfunding success is if the existing audience is already large.

**Comment by anthonye2007** [comment]
have to convince people that idea is worthwhile

**Comment by anthonye2007** [comment]
"It might be useful to use Kickstarter for gauging demand for a project: use it as a sort of preorder system where if you get enough preorders, you greenlight the project."

**Comment by anthonye2007** [comment]
need pre-existing audience and substantial marketing

**Comment by anthonye2007** [comment]
Adds dimension for funding:
on the left is **traditional**, on the right is **crowdfunding**.
Traditional funding includes using a publisher as well as having saved up lots of personal or company capitol.

**Comment by denaefordrobin** [comment]
Great.  Sounds good.

I think this is a valuable dimension
