### ISSUE TITLE
 Gameloft accused of “dangerous” work conditions

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#60]
http://www.industrygamers.com/news/gameloft-accused-of-dangerous-work-conditions/

**Comment by anthonye2007** [comment]
New link:  http://gamepolitics.com/2011/07/18/gameloft-accused-039dangerous-working-conditions039

**Comment by anthonye2007** [comment]
Head programmer resigns due to extremely long hours.
Forced overtime causing mistakes, but management wouldn't let programmers go home.

**Comment by anthonye2007** [comment]
Dimension:  crunch
Dimension: mistakes?

**Comment by anthonye2007** [comment]
Added dimension for 'overtime is good' vs 'overtime is bad'

**Comment by denaefordrobin** [comment]
Great
