### ISSUE TITLE
Create Grid v3

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#73]
- Take out work ownership as a dimension but talk about it in developer motivation
- Create 'Quality of life' dimension
  - job stability
  - job turnover
  - crunch
- Remove size as a dimension
- Remove Product Development in Japanese
- Remove user interaction as a dimension but talk about it in Requirement Volatility.

**Comment by anthonye2007** [comment]
@dmford Can you take a look at the png's I uploaded to the Grid folder?  Then close this issue when you're done.

I added [cluster_v3](https://github.com/FrustratedGameDev/Papers/blob/master/Grid/cluster_v3.png) and [repGrid_v3](https://github.com/FrustratedGameDev/Papers/blob/master/Grid/repGrid_v3.png).

And here's the link to the grid:  http://repertorygridtool.com/grids/show/5SID1lvcDpeOHkbnp6rW

**Comment by denaefordrobin** [comment]
I reviewed them.
