### ISSUE TITLE
Decide on writing process

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#83]
@dmford Just wondering what we should do in terms of review of each other's writings (asking cuz I just finished part of a draft and wasn't sure what to do).

We don't have a ton of time to review each other's work, but reviewing might help catch some mistakes.

I'm suggesting we at least skim everything but only review in depth if asked.  For instance, I just wrote up some of the Methodology stuff and its not very complex so I don't think it needs much attention. But would still be good for you to skim it and make sure the general flow is fine.

However, the intro is more important, so when I get to that I'd want you to spend a little more time on it.  You could make small edits yourself and then use comments or something for bigger issues.

If this sounds good, I'd suggest using labels like we did for papers.  Possible steps:
1. Create new GitHub issue, assign `writing` label, assign to self
2. Start writing, add `in progress` label to issue
3. Finish draft, either change label to `needs skim` or `needs review`, assign to other person
4. Other person either comments and closes if fine or comments, moves back to `in progress` and re-assigns to writer.

Thoughts?  Feel free to suggest something totally different :)

**Comment by denaefordrobin** [comment]
Sounds good. I doubt I'll use all of those throughout because I'll be going through all at once.
