### ISSUE TITLE
Complete references from first half

### ISSUE THREAD

**Issue by anthonye2007** [FrustratedGameDev/Papers#88]
We need to put our references in the final report (we can ignore the seperate files now).

Example format taken from the [markdown spec](http://daringfireball.net/projects/markdown/syntax#link)

```
I get 10 times more traffic from [Google] [1] than from
[Yahoo] [2] or [MSN] [3].

  [1]: http://google.com/        "Google"
  [2]: http://search.yahoo.com/  "Yahoo Search"
  [3]: http://search.msn.com/    "MSN Search"
```

**Comment by denaefordrobin** [comment]
I complete the same references as you did in the second half of the paper.

**Comment by denaefordrobin** [comment]
@anthonye2007 I just noticed that you may want to make changes to yours so I reopened this issue.

**Comment by anthonye2007** [comment]
@dmford I looked my references over and didn't see anything that needed to be changed -- are you thinking of anything specifically?

**Comment by anthonye2007** [comment]
Found and fixed some missing references.
