### ISSUE TITLE
Move Methodolgy -  'Merging Dimensions on Grid' to Top of Results

### ISSUE THREAD

**Issue by denaefordrobin** [FrustratedGameDev/Papers#94]
- Move Merging Dimensions on Grid to Results section.
- Be sure to include the corresponding Rep Grid with them.

**Comment by denaefordrobin** [comment]
@anthonye2007 After looking at this again. I think this is fine where it is.  If you feel the same you can go ahead and close this issue.

I'm thinking that we can add the grids here that were mentioned in #91

**Comment by anthonye2007** [comment]
Looks good to me!
